# python基础语法之数据类型

## 1 字符串(str)

Python中的字符串用单引号（'）或双引号（"）括起来。创建字符串只要为变量分配一个值即可，例如：
str1 = "Hello World!"
Python访问字符串，可以使用方括号（[]）来截取字符串，基本语法如下：
变量[头下标: 尾下标]
其中下标最小的索引值以0为开始值，-1为从末尾的开始位置。Python中的字符串有两种索引方式，从左往右以0开始，从右往左以-1开始。


### 1.1 find, rfind, index, rindex, count的具体应用

find()和rfind()方法分别用来查找一个字符串在另一个字符串指定的范围中首次和最后一次出现的位置，如果不存在则返回-1；index()和rindex()方法用来返回一个字符串在另一个字符串指定范围中首次和最后一次出现的位置，如果不存在则抛出异常；count()方法用来返回一个字符串在另一个字符串中出现的次数，如果不存在则返回0。


In [1]:
str1 = 'Hello World'    #这是我们给出的一个字符串
t1 = str1.find('l')     #2是第一次出现的位置
t2 = str1.rfind('l')    #9是最后一次出现的位置
t3 = str1.index('l')    #2
t4 = str1.index('l')    #区别只有返回不同，这如果不正确就只会返回错误信息，而前面那两个只会返回-1
t5 = str1.count('l')    #3
print(t1, t2, t3, t4, t5)

2 9 2 2 3


### 1.2 split, rsplit的应用

字符串对象的split()和rsplit()方法分别用来以指定字符为分隔符，从字符串左端和右端开始将其分割成多个字符串，并返回包含分隔结果的列表。

对于split()和rsplit()方法，如果不指定分隔符，则字符串中的任何空白字符（包括空格、换行符、制表符等）的连续出现都将被认为是分隔符，并且***自动删除字符串两侧的空白字符***，返回包含最终分隔结果的列表。

In [2]:
str2 = 'Oh my brother this is you'  #只是我们给出的第二个字符串
t1 = str2.split()
t2 = str2.rsplit()
print(t1)
print(t2)

['Oh', 'my', 'brother', 'this', 'is', 'you']
['Oh', 'my', 'brother', 'this', 'is', 'you']


### 1.3 join的应用

字符串的join()方法用来将列表中多个***字符串***进行连接，并在相邻两个字符串之间插入指定字符，返回新字符串。

In [3]:
str3 = '-'
seq1 = ('1', '2', '3')    #元组, 注意里面是字符串
seq2 = ['1', '2', '3']    #列表
str3_1 = str3.join(seq1)
str3_2 = str3.join(seq2)
print(str3_1, str3_2)

1-2-3 1-2-3


### 1.4 strip, rstrip, lstrip的应用

这几个方法分别用来删除两端、右端或左端连续的空白字符或指定字符。

In [4]:
str4 = ' my god '
str4_1 = str4.rstrip()
str4_2 = str4.lstrip()
str4_3 = str4.strip()
print(str4_1)
print(str4_2)
print(str4_3)   #这两个可能不太能看得出来，知道就行了

 my god
my god 
my god


### 1.5 startswith, endswithd的应用

这两个方法用来判断字符串是否以指定字符串开始或结束，可以接收两个整数参数来限定字符串的检测范围。
另外，这两个方法还可以接收一个字符串元组作为参数来表示前缀或后缀。


In [5]:
str5 = '12414235346'
t1 = str5.startswith('12')
t2 = str5.startswith('21')
t3 = str5.endswith('46')
t4 = str5.endswith('5')
print(t1, t2, t3, t4)

True False True False


### 1.6 文本示例

统计下列五行字符串中字符a、c、g、t出现的频数。
1.aggcacggaaaaacgggaataacggaggaggacttggcacggcattacacggagg
2.cggaggacaaacgggatggcggtattggaggtggcggactgttcgggga
3.gggacggatacggattctggccacggacggaaaggaggacacggcggacataca
4.atggataacggaaacaaaccagacaaacttcggtagaaatacagaagctta
5.cggctggcggacaacggactggcggattccaaaaacggaggaggcggacggaggc


In [6]:
import numpy as np
a = []
with open('data2_2') as f:
    for(i, s) in enumerate(f):  #使用 enumerate(f) 遍历文件的每一行，i 是行号（从 0 开始），s 是当前行的字符串内容。
        a.append([s.count('a'), s.count('c'),
                  s.count('g'), s.count('t')])
b = np.array(a)
print(b)

[[19 10 21  5]
 [10  7 24  8]
 [16 12 21  5]
 [24  9 10  8]
 [14 13 24  4]]


## 2 列表(list)

list（列表）是Python中使用最频繁的数据类型。列表可以完成大多数集合类的数据结构的实现。列表中元素的类型可以不相同，它支持数字、字符串，甚至可以包含其他列表（嵌套）。

列表是写在方括号（[]）里、用逗号分隔开的元素列表。和字符串一样，列表同样可以被索引和截取，列表被截取后返回一个包含所需元素的新列表。



### 2.1 截取

列表截取的语法格式如下：
变量[头下标: 尾下标]
索引值的取值和字符串类似，其中下标最小的索引值以0为开始值，以-1为从末尾的开始位置。
与Python字符串不同的是，列表中的元素是可以改变的。

In [7]:
L = ['abc', 12, 3.45, 'Python', 2.789]
print(L)                    #输出完整列表
print(L[0])                 #输出列表的第一个元素
L[0] = 'a'                  #修改列表的第一个元素
L[1:3] = ['b', 'Hello']     #修改列表的第二、三元素
print(L)
L[2:4] = []                 #删除列表的第三、四元素
print(L)

['abc', 12, 3.45, 'Python', 2.789]
abc
['a', 'b', 'Hello', 'Python', 2.789]
['a', 'b', 2.789]


### 2.2 列表推导式

列表推导式可以使用非常简洁的方式对列表或其他可迭代对象的元素进行遍历、过滤或再次计算，快速生成满足特定需求的新列表。列表推导式的语法形式为：

        [expression for expr1 in sequence1 if condition1
                  for expr2 in sequence2 if condition2
                  …
                  for exprN in sequenceN if conditionN]

列表推导式在逻辑上等价于一个循环语句，只是形式上更加简洁。


In [8]:
a = [[1 for x in range(10)] for y in range(10)] #定义一个10 * 10的列表
print(a)
h = [[1,2,3],[4,5,6],[7,8,9]]
c = [j for i in h for j in i]                   #常用于将多维列表铺成一行
print(c)

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


#### 2.2.1 列表推导式中的if


使用列表推导式查找数组中最大元素的所有位置。


In [9]:
from numpy.random import randint
import numpy as np
a=randint(10,20,16)  #生成16个[10,20)上的随机整数
ma=max(a)
ind1=[index for index,value in enumerate(a) if value==ma]
ind2=np.where(a==ma)  #第二种方法求最大值的地址
print(ind1); print(ind2[0])

[0, 1, 5]
[0 1 5]


## 3 元组(tyrple)

元组是一个不可改变的列表。不可改变意味着它***不能被修改***。元组只是逗号分隔的对象序列（不带括号的列表）。为了增加代码的可读性，通常将元组放在一对圆括号中

In [10]:
#四种方法
my_tuple1 = 1,2,3
my_tuple2 = (1,2,3)
my_tuple3 = 1,
my_tuple4 = tuple([1,2,3])
print(my_tuple1)
print(my_tuple2)
print(my_tuple3)
print(my_tuple4)

(1, 2, 3)
(1, 2, 3)
(1,)
(1, 2, 3)


元组通过英文状态下的圆括号构成，即()。a=()表示a为空元组，b1=(9,)表示b1为只有一个元素9的元组；b2=(9)表示b2为整数9。

In [11]:
my_tuple5 = (9, )
my_tuple6 = (9)
print(type(my_tuple5), type(my_tuple6))

<class 'tuple'> <class 'int'>


与列表最大的区别是，元组不再是一种可变类型的数据结构。由于元组只是存储数据的不可变容器，因此其只有两种可用的“方法”，分别是count和index，它们的功能与列表中的count和index方法完全一样。

元组仍然是一种序列，所以几种获取列表元素的索引方法同样可以使用到元组对象中。

### 3.1 其他零碎小知识

我们可以使用元组的小技巧为`a, b, c = 1, 2, 3`，显然等式右边是元组的定义

In [12]:
a, b, c = 1, 2, 3
print(a, b, c)

1 2 3


## 4 集合(set)

集合（set）是一个无序不重复元素的序列。基本功能是进行成员关系测试和删除重复元素。

在Python中，创建集合有两种方式：一种是用一对大括号将多个用逗号分隔的数据括起来；另一类是使用set()函数，该函数可以将字符串、列表、元组等类型的数据转换成集合类型的数据。

***但是我们不能像列表一样直接用{}创建一个空集合，因为会和dic冲突***

### 4.1 集合的应用

集合中不能有相同元素，如果在创建集合时有重复元素，Python会自动删除重复的元素。集合的这个特性非常有用，例如，要删除列表中大量重复的元素，可以先用set()函数将列表转换成集合，再用list()函数将集合转换成列表，操作效率非常高。

In [13]:
a = set('abcdabc')
print(a)  #每次输出是不一样的，如输出：{'d', 'b', 'a', 'c'}

{'b', 'd', 'c', 'a'}


## 5 字典

字典（dictionary）是Python中另一个非常有用的内置数据类型。前面介绍的列表是有序的对象集合，字典是无序的对象集合。两者的区别在于：字典中的元素是通过键来存取的，而不是通过索引值存取的。

字典是一种映射类型，字典用“{}”标识，它是一个无序的键（key）：值（value）对集合。在同一个字典中，键（key）必须是唯一的，但是值则不必唯一，值可以取任何数据类型，但***键必须是不可变的，如字符串、数字或元组。***


In [14]:
dict1 ={'Alice': '123', 'Beth': '456', 'Cecil': 'abc'}
print(dict1['Alice'])   #输出123
dict1['new'] = 'Hello'  #增加新的键值对
dict1['Alice'] = '1234' #修改已有键值对
dict2 = {'abc': 123, 456: 78.9}
print(dict2[456])       #输出78.9

123
78.9


### 5.1 get函数

字典对象提供了一个get()方法用来返回指定“键”对应的“值”，并且允许指定该键不存在时返回特定的“值”。


In [15]:
Dict={'age':18,'score':[98,97],'name':'Zhang','sex':'male'}
print(Dict['age'])          #输出18
print(Dict.get('age'))      #输出18
print(Dict.get('address','Not Exists.'))   #输出No Exists

18
18
Not Exists.


### 5.2 字典的访问

我们可以用`in Dict`和`in Dict.keys()`来遍历键，用`in Dict.items()`遍历所有元素，用`in Dict.values()`来遍历所有值

In [16]:
Dict={'age':18, 'score':[98,97], 'name':'Zhang', 'sex':'male'}
for item in Dict.keys():            #遍历输出字典的“键”
    print(item)
print("----------" )
for item in Dict.items():           #遍历输出字典的元素，并且是元组的形式
    print(item)
print("----------")
for value in Dict.values():         #遍历输出字典的值
    print(value)
print("----------")
for item in Dict:                 #遍历输出字典的“键”
    print(item)

age
score
name
sex
----------
('age', 18)
('score', [98, 97])
('name', 'Zhang')
('sex', 'male')
----------
18
[98, 97]
Zhang
male
----------
age
score
name
sex


### 5.3 字典应用示例

首先生成包含1000个随机字符的字符串，然后统计每个字符的出现次数，注意get()方法的应用。

基本思路：在Python标准库`string`中，`ascii_letters`表示英文大小写字符，`digits`表示10个数字字符。本例中使用字典存储每个字符的出现次数，其中键表示字符，对应的值表示出现次数。在生成随机字符串时使用了生成器表达式，`''.join(…)`的作用是使用空字符把参数中的字符串连接起来成为一个长字符串。最后使用for循环遍历该长字符串中的每个字符，把每个已出现字符的次数加1，如果是第一次出现，则已出现次数为0。

In [19]:
import string
import random
x = string.ascii_letters + string.digits #x合并后为包含62个字符的字符串（大小写字母 + 数字）。
y=''.join([random.choice(x) for i in range(1000)])
#choice()用于从多个元素中随机选择一个
d=dict()  #构造空字典
for ch in y:
    d[ch]=d.get(ch,0)+1;
for k,v in sorted(d.items()): #按AC排序输出
    print(k,':',v)

0 : 16
1 : 17
2 : 21
3 : 16
4 : 17
5 : 13
6 : 8
7 : 10
8 : 11
9 : 14
A : 17
B : 15
C : 17
D : 10
E : 17
F : 17
G : 14
H : 21
I : 20
J : 16
K : 17
L : 13
M : 18
N : 14
O : 19
P : 14
Q : 21
R : 6
S : 15
T : 13
U : 18
V : 18
W : 20
X : 14
Y : 16
Z : 15
a : 14
b : 17
c : 19
d : 11
e : 18
f : 11
g : 22
h : 19
i : 28
j : 12
k : 16
l : 14
m : 13
n : 15
o : 20
p : 17
q : 20
r : 15
s : 15
t : 18
u : 17
v : 17
w : 16
x : 36
y : 14
z : 8
