# python语法之函数

在Python语言中，函数是一组相关联的、能够完成特定任务的语句模块，分内置函数、第三方模块函数和自定义函数。内置函数是Python系统自带的函数，模块函数是NumPy等库中的函数。下面先介绍自定义函数。


## 1.自定义函数

Python中定义函数的语法如下：

        def functionName(formalParameters)：
                functionBody


In [1]:
def factorial(n):  #定义阶乘函数
    r = 1
    while n > 1:
        r *= n
        n -= 1
    return r

def fib(n):   #定义输出斐波那契数列函数
    a, b = 1, 1
    while a < n:
        print(a, end='  ')
        a, b = b, a+b

print('%d!= %d'%(5,factorial(5)))
fib(200)


5!= 120
1  1  2  3  5  8  13  21  34  55  89  144  

我们也可以先编写求阶乘和输出斐波那契数列的两个函数，并保存在文件ex2_1_2.py中，供其他程序调用。


In [2]:
from ex2_12_2 import factorial, fib
print('%d!= %d'%(5,factorial(5)))
fib(200)

5!= 120
1  1  2  3  5  8  13  21  34  55  89  144  

数据分组

In [3]:
def bifurcate_by(L, fn):
    return [[x for x in L if fn(x)],
            [x for x in L if not fn(x)]]
s=bifurcate_by(['beep', 'boop', 'foo', 'bar'], lambda x: x[0] == 'b')
print(s)

[['beep', 'boop', 'bar'], ['foo']]


## 2 匿名函数

所谓匿名函数，是指不以def语句定义的没有名称的函数，它在使用时临时声明、立刻执行，其特点是执行效率高。
Python使用`lambda`来创建匿名函数，它是一个可以接收任意多个参数并且返回单个表达式值的函数，其语法格式为：

        lambda arg1[，arg2，…，argn]：expression

In [4]:
f = lambda x, y, z: x * y * z
L = lambda x: [x ** 2, x ** 3, x ** 4]
print(f(3,4,5)); print(L(2))

60
[4, 8, 16]


## 3 模块的导入与使用

随着程序的变大及代码的增多，为了更好地维护程序，一般会把代码进行分类，分别放在不同的文件中。公共类、函数都可以放在独立的文件中，这样其他多个程序都可以使用，而不必把这些公共的类、函数等在每个程序中复制一份，这样独立的文件就叫做模块。

标准库中有与时间相关的time、datetime模块，随机数的random模块，与操作系统交互的os模块，对Python解释器相关操作的sys模块，数学计算的math模块等几十个模块。

### 3.1 import 模块名 [as 别名]

In [5]:
import math               #导入标准库math
import random             #导入标准库random
import numpy.random as nr  #导入numpy库中的random模块
a=math.gcd(12,21)          #计算最大公约数，a=3
b=random.randint(0,2)       #获得[0,2]区间上的随机整数
c=nr.randint(0, 2, (4, 3))      #获得[0,2)区间上的4×3随机整数矩阵
print(a); print(b); print(c)      #输出a,b,c的值

3
0
[[1 1 0]
 [0 1 1]
 [0 1 1]
 [1 1 0]]


### 3.2 from 模块名 import 对象名 [as 别名]

In [6]:
from random import sample
from numpy.random import randint
a=sample(range(10), 5)  #在[0,9]区间上选择不重复的5个整数
b=randint(0, 10, 5)      #在[0,9]区间上生成5个随机整数
print(a); print(b)

[6, 9, 3, 4, 0]
[4 9 7 4 0]


### 3.3 from 模块名 import *

In [7]:
from math import *
a=sin(3)         #求正弦值
b=pi             #常数π
c=e              #常数e
d=radians(180)   #把角度转换为弧度
print(a); print(b); print(c); print(d)

0.1411200080598672
3.141592653589793
2.718281828459045
3.141592653589793


## 4 自定义函数的导入


在Python中，每个包含函数的Python文件都可以作为一个模块使用，其模块名就是文件名。

可以从[这里](#1自定义函数)找到你想要的

## 5 Python常用内置函数用法

内置函数不需要额外导入任何模块即可直接使用，具有非常快的运行速度，推荐优先使用。使用下面的语句可以查看所有内置函数和内置对象。

        dir(__builtins__)
使用help(函数名)可以查看某个函数的用法。常用的内置函数及其功能简要说明如表2.3所示。


### 5.1 排序(sortef)

sorted()可以对列表、元组、字典、集合或其他可迭代对象进行排序并返回新列表，支持使用key参数指定排序规则。

In [8]:
import numpy.random as nr
x1 = list(range(9, 21))
nr.shuffle(x1)
x2 = sorted(x1)
x3 = sorted(x1, reverse = True)
x4 = sorted(x1, key = lambda item : len(str(item)))
print(x1); print(x2); print(x3); print(x4)

[18, 9, 12, 15, 11, 13, 17, 14, 16, 10, 19, 20]
[9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9]
[9, 18, 12, 15, 11, 13, 17, 14, 16, 10, 19, 20]


### 5.2 枚举(enumerate)


enumerate()函数用来枚举可迭代对象中的元素，返回可迭代的enumerate对象，利用该函数可同时获得索引和值。在使用时，既可以把enumerate对象转换为列表、元组、集合，也可以使用for循环直接遍历其中的元素。

In [9]:
x1="abcde"
x2=list(enumerate(x1))
for ind,ch in enumerate(x1): print(ch, end = ' '); print(ind, end = ' ')

a 0 b 1 c 2 d 3 e 4 

### 5.3 map()函数

函数map(func, *iterables)把一个函数func依次映射到一个可迭代对象iterables的每个元素上，并返回一个可迭代的map对象作为结果，map对象中每个元素是iterables中元素经过函数func处理后的结果。

In [10]:
import random

# 生成 [100000, 99999999] 的随机整数
x = random.randint(10**5, 10**8 - 1)
y = list(map(int, str(x)))  # 提取每位数字

# 使用等长列表测试逻辑
list1 = [1, 3, 2, 4, 1]
list2 = [3, 2, 1, 2, 4]  # 补充长度
z = list(map(lambda x,y: x%2==1 and y%2==0, list1, list2))

print(x)
print(y)
print(z)

95615962
[9, 5, 6, 1, 5, 9, 6, 2]
[False, True, False, False, True]


### 5.4 filter()函数


内置函数filter()将一个单参数函数作用到一个序列上，返回该序列中使得该函数取值为True的那些元素组成的filter对象，可以把filter对象转换为列表、元组、集合，也可以直接使用for循环遍历其中的元素。

In [11]:
a = filter(lambda x : x > 10, [1,11,2,45,7,6,13])
b = filter(lambda x:  x.isalnum(), ['abc', 'xy12', '***'])
#isalnum()是测试是否为字母或数字的方法
print(list(a)); print(list(b))

[11, 45, 13]
['abc', 'xy12']


还可以过滤重复值


In [12]:
def filter_non_unique(L):
    return [item for item in L if L.count(item) == 1]
a = filter_non_unique([1, 2, 2, 3, 4, 4, 5])
print(a)
a = list(set([1, 2, 2, 3, 4, 4, 5]))
print(a)

[1, 3, 5]
[1, 2, 3, 4, 5]


### 5.5 zip()函数


zip()函数用来把多个可迭代对象中对应位置上的元素压缩在一起，返回一个可迭代的zip对象，其中每个元素都是包含原来多个可迭代对象对应位置上元素的元组，最终结果中包含的元素个数取决于所有参数序列或可迭代对象中最短的那个。

In [13]:
s1=[str(x)+str(y) for x, y in zip(['v']*4, range(1,5))]
s2=list(zip('abcd', range(4)))
print(s1); print(s2)

['v1', 'v2', 'v3', 'v4']
[('a', 0), ('b', 1), ('c', 2), ('d', 3)]
