# NumPy库

标准安装的Python中用列表（list）保存的一组值，可以用来当作数组使用，但是由于列表的元素可以是任意对象，因此列表中所保存的是对象的指针。这样为了保存一个简单的[1, 2, 3]，需要有3个指针和3个整数对象。对于数值运算来说，这种结构显然比较浪费内存和CPU的计算时间。
此外，Python还提供了一个array模块。array对象和列表不同，它直接保存数值，和C语言的一维数组比较类似。但是由于它不支持多维，也没有各种运算函数，因此也不适合做数值运算。
NumPy的诞生弥补了这些不足，NumPy提供了两种基本的对象：ndarray（N-dimensional array object）存储单一数据类型的多维数组；ufunc（universal function object）能够对数组进行处理的函数。

进一步学习可以参考[这个](https://www.runoob.com/numpy/numpy-tutorial.html)

## 1 数组的创建


1. 使用`array`将列表或元组转换为ndarray数组。
2. 使用`arange`在给定区间内创建等差数组，其调用格式为
arange(start=None, stop=None, step=None, dtpye=None)`
生成区间[start, stop)上步长间隔为step的等差数组。
3. 使用`linspace`在给定区间内创建间隔相等的数组。其调用格式为
`linspace(start, stop, num=50, endpoint=True)`
生成区间[start, stop]上间隔相等的num个数据的等差数组，num的默认值为50。
4. 使用`logspace`在给定区间上生成等比数组。其调用格式为
`logspace(start, stop, num=50, endpoint=True, base=10.0)`
默认生成区间 上的num个数据的等比数组。
5. 使用ones、zeros、empty和ones_like等系列函数

In [1]:
import numpy as np
a1 = np.array([1, 2, 3, 4])   #生成整型数组
a2 = a1.astype(float)
a3 = np.array([1, 2, 3, 4], dtype=float)   #浮点数
print(a1.dtype); print(a2.dtype); print(a3.dtype)
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.arange(1,5)        #生成数组[1, 2, 3, 4]
d = np.linspace(1, 4, 4)  #生成数组[1, 2, 3, 4]
e = np.logspace(1, 3, 3, base=2)  #生成数组[2, 4, 8]
print(b); print(c); print(d); print(e)

int64
float64
float64
[[1 2 3]
 [4 5 6]]
[1 2 3 4]
[1. 2. 3. 4.]
[2. 4. 8.]


In [2]:
import numpy as np
a = np.ones(4, dtype=int)     #输出[1, 1, 1, 1]
b = np.ones((4,), dtype=int)  #同a
c = np.ones((4,1))             #输出4行1列的数组
d = np.zeros(4)               #输出[0, 0, 0, 0]
e = np.empty(3)               #生成3个元素的空数组行向量
f = np.eye(3)                 #生成3阶单位阵
g = np.eye(3, k=1)  #生成第k对角线的元素为1，其他元素为0的3阶方阵
h = np.zeros_like(a)          #生成与a同维数的全0数组
print(a); print(b); print(c); print(d); print(e); print(f); print(g); print(h)

[1 1 1 1]
[1 1 1 1]
[[1.]
 [1.]
 [1.]
 [1.]]
[0. 0. 0. 0.]
[2. 4. 8.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[0 0 0 0]


## 2 元素数组的索引

NumPy中的array数组与Python基础数据结构列表（list）的区别是：列表中的元素可以是不同的数据类型，而array数组只允许存储相同的数据类型。
1. 对于一维数组来说，Python原生的列表和NumPy的数组的切片操作都是相同的，无非是记住一个规则：列表名（或数组名）[start: end: step]，但不包括索引end对应的值。
2. 二维数据列表元素的引用方式为a[i][j]；array数组元素的引用方式还可以为a[i,j]。
3. NumPy比一般的Python 序列提供更多的索引方式。除了用整数和切片的一般索引外，数组还可以布尔索引及花式索引。

In [3]:
import numpy as np
a = np.arange(16).reshape(4,4)  #生成4行4列的数组
b = a[1][2]   #输出6
c = a[1, 2]   #同b
d = a[1:2, 2:3]  #输出[[6]]
x = np.array([0, 1, 2, 1])
print(a[x==1])  #输出a的第2、4行元素
print(a)
print(b); print(c); print(d);

[[ 4  5  6  7]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
6
6
[[6]]


## 3 矩阵分割

### 3.1 矩阵的合并


在实际应用中，经常需要合并矩阵，可以用vstack([A, B])和hstack([A, B])实现不同轴上的合并。vstack（）是一个将矩阵上下合并的函数，而hstack()则是左右合并的函数。

In [4]:
import numpy as np
a = np.arange(16).reshape(4,4)  #生成4行4列的数组
b = np.floor(5 * np.random.random((2, 4))) #floor向下取整
c = np.ceil(6*np.random.random((4, 2)))  #ceil向上取整
d = np.vstack([a, b])  #上下合并矩阵
e = np.hstack([a, c])  #左右合并矩阵
print(a); print(b); print(c); print(d); print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[4. 3. 3. 4.]
 [0. 4. 1. 1.]]
[[5. 5.]
 [1. 5.]
 [6. 4.]
 [5. 4.]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [ 4.  3.  3.  4.]
 [ 0.  4.  1.  1.]]
[[ 0.  1.  2.  3.  5.  5.]
 [ 4.  5.  6.  7.  1.  5.]
 [ 8.  9. 10. 11.  6.  4.]
 [12. 13. 14. 15.  5.  4.]]


### 3.2 矩阵分割

vsplit(a, m)把a平均分成m个行vsplit(a, m)把a平均分成m个行数组，hsplit(a, n)把a平均分成n个列数组。数组，hsplit(a, n)把a平均分成n个列数组。

In [5]:
import numpy as np
a = np.arange(16).reshape(4,4)  #生成4行4列的数组
b = np.vsplit(a, 2)             #行分割
print(a)
print('行分割：\n', b[0], '\n', b[1])
c = np.hsplit(a, 4)             #列分割
print('列分割：\n', c[0], '\n', c[1], '\n', c[2], '\n', c[3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
行分割：
 [[0 1 2 3]
 [4 5 6 7]] 
 [[ 8  9 10 11]
 [12 13 14 15]]
列分割：
 [[ 0]
 [ 4]
 [ 8]
 [12]] 
 [[ 1]
 [ 5]
 [ 9]
 [13]] 
 [[ 2]
 [ 6]
 [10]
 [14]] 
 [[ 3]
 [ 7]
 [11]
 [15]]


### 5.3 数组元素的索引

对于一维数组来说，Python原生的列表和NumPy的数组的切片操作都是相同的，无非是记住一个规则：列表名（或数组名）[start: end: step]，但不包括索引end对应的值。

In [6]:
import numpy as np
a = np.arange(16).reshape(4,4)  #生成4行4列的数组
b = a[1][2]   #输出6
c = a[1, 2]   #同b
d = a[1:2, 2:3]  #输出[[6]]
x = np.array([0, 1, 2, 1])
print(a[x==1])  #输出a的第2、4行元素

[[ 4  5  6  7]
 [12 13 14 15]]


## 6 矩阵的简单运算

### 6.1 求和

In [7]:
import numpy as np
a = np.array([[0, 3, 4], [1, 6, 4]])
b = a.sum()   #使用方法，求矩阵所有元素的和
c1 = sum(a)   #使用内置函数，求矩阵逐列元素的和
c2 = np.sum(a, axis=0) #使用函数，求矩阵逐列元素的和
c3 = np.sum(a, axis=0, keepdims=True)   #逐列求和
print(c2.shape, c3.shape)  #c2是(3,)数组，c3是(1,3)数组
print(c1); print(c2); print(c3)

(3,) (1, 3)
[1 9 8]
[1 9 8]
[[1 9 8]]


### 6.2 逐个运算

对于ndarray数组，+、-、*、/都是对应的逐个元素运算。乘幂运算**也是对应逐个元素运算。

In [8]:
import numpy as np
a = np.array([[0, 3, 4], [1, 6, 4]])
b = np.array([[1, 2, 3], [2, 1, 4]])
c = a / b   #两个矩阵对应元素相除
d = np.array([2, 3, 2])
e = a * d   #d先广播成与a同维数的矩阵，再逐个元素相乘
f = np.array([[3],[2]])
g = a * f   #f先广播成与a同维数的矩阵，再逐个元素相乘
h = a ** (1/2)  #a矩阵逐个元素的1/2次幂。
print(a); print(b); print(c); print(d); print(e); print(f); print(g); print(h)

[[0 3 4]
 [1 6 4]]
[[1 2 3]
 [2 1 4]]
[[0.         1.5        1.33333333]
 [0.5        6.         1.        ]]
[2 3 2]
[[ 0  9  8]
 [ 2 18  8]]
[[3]
 [2]]
[[ 0  9 12]
 [ 2 12  8]]
[[0.         1.73205081 2.        ]
 [1.         2.44948974 2.        ]]


### 6.3 矩阵乘法

In [9]:
import numpy as np
a = np.ones(4)
b = np.arange(2, 10, 2)
c = a @ b  #a作为行向量, b作为列向量
d = np.arange(16).reshape(4,4)
f = a @ d  #a作为行向量
g = d @ a  #a作为列向量
print(a); print(b); print(c); print(d); print(e); print(f); print(g);

[1. 1. 1. 1.]
[2 4 6 8]
20.0
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  9  8]
 [ 2 18  8]]
[24. 28. 32. 36.]
[ 6. 22. 38. 54.]


## 7 矩阵运算与线性代数

### 7.1 范数计算


计算范数的函数`norm`的调用格式如下：

        norm(x, ord=None, axis=None, keepdims=False)
其中：

`x`: 表示要度量的向量或矩阵；

`ord`: 表示范数的种类，例如1范数，2范数， 范数。

`axis`: `axis=1`表示按行向量处理，求多个行向量的范数；`axis=0`表示按列向量处理，求多个列向量的范数；`axis=None`表示矩阵范数。

`keepdims`: 是否保持矩阵的二维特性。`True`表示保持矩阵的二维特性，`False`则相反。


求
$$
\begin{bmatrix}
0 & 3 & 4\\
1 & 6 & 4\\
\end{bmatrix}
$$
的各个行向量的2范数，各个列向量的2范数和矩阵2范数。


In [10]:
a = np.array([[0, 3, 4], [1, 6, 4]])
b = np.linalg.norm(a, axis=1)  #求行向量2范数
#默认行为：不指定 ord 参数时，np.linalg.norm 计算的是 Frobenius 范数（所有元素平方和的平方根）。
c = np.linalg.norm(a, axis=0)  #求列向量2范数
d = np.linalg.norm(a)   #求矩阵2范数
print('行向量2范数为：', np.round(b, 4))
print('列向量2范数为：', np.round(c, 4))
print('矩阵2范数为：', round(d, 4))

行向量2范数为： [5.     7.2801]
列向量2范数为： [1.     6.7082 5.6569]
矩阵2范数为： 8.8318


关键区别总结

| 范数类型	      | 计算方法	         | 代码参数  |
|------------|---------------|-------|
| 行向量  2-范数	 |每行元素的平方和的平方根	|axis=1|
| 列向量 2-范数	  | 每列元素的平方和的平方根	 | axis=0 |
|矩阵 Frobenius 范数	|所有元素的平方和的平方根	|默认（不指定 ord）
矩阵谱范数（2-范数）	|最大奇异值	|ord=2

### 7.2 求解线性方程组唯一解

求解方程组
$$
\begin{cases}
3x + y = 9\\
x + 2y = 8\\
\end{cases}
$$

In [11]:
import numpy as np
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x1 = np.linalg.inv(a) @ b
x2 = np.linalg.solve(a, b)
print(x1); print(x2)

[2. 3.]
[2. 3.]


### 7.3 求超定方程组的最小二乘解

求解线性方程组
$$
\begin{cases}
3x + y = 9\\
x + 2y = 8\\
x + y = 6\\
\end{cases}
$$

In [12]:
import numpy as np
a = np.array([[3, 1], [1, 2], [1, 1]])
b = np.array([9, 8, 6])
x = np.linalg.pinv(a) @ b
print(np.round(x, 4))

[2.     3.1667]


### 7.4 求下列矩阵的特征值和特征向量
$$
\begin{bmatrix}
0 & 0 & 0 & 1\\
0 & 0 & 1 & 0\\
0 & 1 & 0 & 0\\
1 & 0 & 0 & 0\\
\end{bmatrix}
$$

In [13]:
import numpy as np
a = np.eye(4)
b = np.rot90(a)
c, d = np.linalg.eig(b)
print('特征值为：', c)
print('特征值为：\n', d)

特征值为： [ 1. -1.  1. -1.]
特征值为：
 [[ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678 -0.70710678]
 [ 0.          0.          0.70710678  0.70710678]
 [ 0.70710678 -0.70710678  0.          0.        ]]
