# Scipy介绍

SciPy是在NumPy库的基础上增加了众多的数学、科学以及工程计算中常用函数的库。SciPy库依赖于NumPy，提供了便捷且快速的 维数组操作。SciPy库与NumPy数组一起工作，提供了许多友好和高效的处理方法，它包括了统计、优化、线性代数模块、傅里叶变换、信号、图像处理和常微分方程的求解等，功能十分强大

如果想了解更多，可以点击[这里](https://www.runoob.com/scipy/scipy-tutorial.html)

SciPy被组织成覆盖不同科学计算领域的模块，具体见表2.7。
<center>表2.7  SciPy模块功能表</center>

|模块	|功能	|模块	|功能|
|---|---|---|---|
|scipy.cluster	|聚类分析等	|scipy.odr	|正交距离回归|
|scipy.constants	|物理和数学常数	|scipy.optimize|	优化|
|scipy.fftpack	|傅里叶变换	|scipy.signal	|信号处理|
|scipy.integrate	|积分	|scipy.sparse	|稀疏矩阵|
|scipy.interpolate	|插值	|scipy.spatial	|空间数据结构和算法|
|scipy.io	|数据输入和输出	|scipy.special	|特殊函数|
|scipy.linalg	|线性代数	|scipy.stats	|统计|
|scipy.ndimage	|n维图像|


## 1 求解方程组
`scipy.optimize`模块的`fsolve`和`root`不仅可以求非线性方程的解，而且也可以求非线性方程组的解。它们的调用格式为：

        from scipy.optimize import fsolve
        from scipy.optimize import root


### 1.1 例题一
求方程
$$
x^{980}-5.01x^{979}+7.398x^{978}-3.388x^{977}-x^3+5.01x^{2}-7.398x+3.388=0
$$
在给定初值1.5附近的一个实根。


In [6]:
from scipy.optimize import fsolve, root
fx = lambda x:     x**980-5.01*x**979+7.398*x**978\
    -3.388*x**977-x**3+5.01*x**2-7.398*x+3.388
x1 = fsolve(fx, 1.5, maxfev=4000)  #函数调用4000次
x2 = root(fx, 1.5)
print(x1,'\n','-------------'); print(x2)

[1.21] 
 -------------
 message: The solution converged.
 success: True
  status: 1
     fun: [-1.235e+69]
       x: [ 1.210e+00]
  method: hybr
    nfev: 321
    fjac: [[-1.000e+00]]
       r: [ 2.542e+80]
     qtf: [ 2.002e+72]


### 1.2 例题二

求方程组
$$
\begin{cases}
x_1^2 + x_2^2 & = & 1\\
x_1 & = & x_2
\end{cases}
$$
的一组数值解。


In [7]:
from scipy.optimize import fsolve, root
fx = lambda x: [x[0]**2+x[1]**2-1, x[0]-x[1]]
s1 = fsolve(fx, [1, 1])
s2 = root(fx, [1, 1])
print(s1,'\n','--------------'); print(s2)

[0.70710678 0.70710678] 
 --------------
 message: The solution converged.
 success: True
  status: 1
     fun: [ 4.441e-16  0.000e+00]
       x: [ 7.071e-01  7.071e-01]
  method: hybr
    nfev: 11
    fjac: [[-8.165e-01 -5.773e-01]
           [ 5.773e-01 -8.165e-01]]
       r: [-1.732e+00 -5.774e-01  1.633e+00]
     qtf: [-3.646e-10  2.578e-10]


## 2 求积分

`scipy.integrate`模块提供了多种积分模式。积分主要分为以下两类：一种是对给定函数的数值积分，见表2.8。另一种是对给定离散点的数值积分，函数有`trapz`。
<center>表2.8  scipy.integrate模块的数值积分函数</center>

| 函数	                                          | 说明       |
|:---------------------------------------------|:---------|
| quad(func, a, b, args)	                      | 计算一重积分   |
| dblquad(func, a, b, gfun, hfun, args)	       | 计算二重数值积分 |
| tplquad(func, a, b, gfun, hfun, qfun, rfun)	 | 计算三重数值积分 |
| nquad(func, ranges, args)	                   | 计算多变量积分  |

### 2.1 例题
分别计算$a = 1, b = 1$；$a = 2, b = 10时，I(a, b) = \int_0^1 {(ax^2 + bx)} \,{\rm d}x$的值

In [8]:
from scipy.integrate import quad
fun46 = lambda x, a, b : a * x ** 2 + b * x
I1 = quad(fun46, 0, 1, args=(2, 1))
I2 = quad(fun46, 0, 1, args=(2, 10))
print(I1); print(I2)

(1.1666666666666665, 1.2952601953960159e-14)
(5.666666666666667, 6.291263806209221e-14)


## 3 最小二乘解

对于非线性方程组
$$
\begin{cases}
f_1(x) & = & 0\\
f_2(x) & = & 0\\
...\\
f_n(x) & = & 0\\
\end{cases}
\tag{3.1}
$$
其中$x$为$m$维向量，一般地，$n>m$，且方程组（3.1）是矛盾方程组，有时需要求方程组（3.1）的最小二乘解，即求下面多元函数
$$
\delta(x) = \sum_{i = 1}^n {f_i^2(x)}
\tag{3.2}
$$
的最小值
·scipy.optimize·模块求非线性方程组最小二乘解的函数调用格式为

        from scipy.optimize import least_squares
        least_squares(fun,x0)
其中`fun`是定义向量函数
$$
[f_1(x) \; f(_2x) \; f_3(x) \; ... \; f_n(x)]^T
$$
的匿名函数的返回值，$x_0$为 的初始值。


### 3.1 例题1
已知4个观测站的位置坐标 ，每个观测站都探测到距未知信号的距离 ，已知数据见表2.9，试定位未知信号的位置坐标 。

表2.9  观测站的位置坐标及探测到的距离

| 	1	  | 2	   |3	|4|
|------|------|---|---|
| 245	 | 164	 | 192	 | 232 |
|442	|480	|281	|300|
|126.2204|	120.7509	|90.1854|	101.4021|


未知信号的位置坐标 满足非线性方程组
$$
\begin{cases}
\sqrt{(x_1 - x)^2 + (y_1 - y)^2} - d_1 & = & 0\\
\sqrt{(x_2 - x)^2 + (y_2 - y)^2} - d_2 & = & 0\\
\sqrt{(x_3 - x)^2 + (y_3 - y)^2} - d_3 & = & 0\\
\sqrt{(x_4 - x)^2 + (y_4 - y)^2} - d_4 & = & 0\\
\end{cases}
\tag{3.1}
$$
显然方程组（3.1）是一个矛盾方程组，必须求方程组（3.1）的最小二乘解。

可以把问题转化为求如下多元函数

$$
\delta(x, y) = \sum_{i = 1}^4 {\sqrt{(x_i - x)^2 + (y_i - y)^2} - d_i}
\tag{3.2}
$$

In [9]:
from scipy.optimize import least_squares
import numpy as np
a=np.loadtxt('data2_47.txt')
x0=a[0]; y0=a[1]; d=a[2]
fx=lambda x: np.sqrt((x0-x[0])**2+(y0-x[1])**2)-d
s=least_squares(fx, np.random.rand(2))
print(s, '\n', '------------', '\n', s.x)

     message: Both `ftol` and `xtol` termination conditions are satisfied.
     success: True
      status: 4
         fun: [-3.433e-01  1.360e-01 -4.966e-01  5.928e-01]
           x: [ 1.495e+02  3.600e+02]
        cost: 0.367150558463682
         jac: [[-7.586e-01 -6.516e-01]
               [-1.199e-01 -9.928e-01]
               [-4.738e-01  8.807e-01]
               [-8.088e-01  5.881e-01]]
        grad: [-1.115e-08  3.907e-09]
  optimality: 1.115069314661099e-08
 active_mask: [ 0.000e+00  0.000e+00]
        nfev: 15
        njev: 15 
 ------------ 
 [149.50894334 359.9847955 ]


## 4 最大模特征值及对应的特征向量


求下列矩阵的最大模特征值及对应的特征向量：
$$
A = \begin{bmatrix}
1 & 2 & 3\\
2 & 1 & 3\\
3 & 3 & 6\\
\end{bmatrix}
$$

In [10]:
from scipy.sparse.linalg import eigs
import numpy as np
a = np.array([[1, 2, 3], [2, 1, 3], [3, 3, 6]], dtype=float)  #必须加float,否则出错
b, c = np.linalg.eig(a)
d, e = eigs(a, 1)
print(b, c)
print('最大模特征值为：', d)
print('对应的特征向量为：\n', e)

[ 9.00000000e+00 -1.00000000e+00  2.80739441e-18] [[-4.08248290e-01 -7.07106781e-01 -5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01 -5.77350269e-01]
 [-8.16496581e-01  4.65265489e-17  5.77350269e-01]]
最大模特征值为： [9.+0.j]
对应的特征向量为：
 [[0.40824829+0.j]
 [0.40824829+0.j]
 [0.81649658+0.j]]
