# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [1]:
import sympy as sp
sp.var('k',positive=True, integer=True)
a = sp.Matrix([[0, 1], [1, 1]])
val = a.eigenvals()   #求特征值
vec = a.eigenvects()  #求特征向量
P, D = a.diagonalize()  #把a相似对角化
ak = P @ (D ** k) @ (P.inv())
F = ak @ sp.Matrix([1, 1])
s = sp.simplify(F[0])
print(s); sm = []
for i in range(20):
    sm.append(s.subs(k, i).n())
print(sm)

(2*(1 - sqrt(5))**k + sqrt(5)*(1 + sqrt(5))**k + 3*(1 + sqrt(5))**k)/(2**k*(sqrt(5) + 5))
[1.00000000000000, 1.00000000000000, 2.00000000000000, 3.00000000000000, 5.00000000000000, 8.00000000000000, 13.0000000000000, 21.0000000000000, 34.0000000000000, 55.0000000000000, 89.0000000000000, 144.000000000000, 233.000000000000, 377.000000000000, 610.000000000000, 987.000000000000, 1597.00000000000, 2584.00000000000, 4181.00000000000, 6765.00000000000]


In [7]:
str1 = '3532314'
str1.startswith('4')

False

In [16]:
import numpy as np
a = []
with open('data2_2') as f:
    for(i, s) in enumerate(f):
        a.append([s.count('a'), s.count('c'),
                  s.count('g'), s.count('t')])
b = np.array(a)
print(b)

[[19 10 21  5]
 [10  7 24  8]
 [16 12 21  5]
 [24  9 10  8]
 [14 13 24  4]]


Heading level 1
===============